[build]
  command = "npm run build"
  publish = "dist"
  node_version = "18"

# SPA fallback (safe to keep, even if you don't use a router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
